### ISSUE TITLE
instrumentald shouldn't show an exception if you `start` it when it's already running.

### ISSUE THREAD

**Issue by jason-o-matic** [Instrumental/instrumentald#12]
```
deploy@smoke-smoke-666 ~ $ sudo /etc/init.d/instrumentald status
"instrumentald" is running (PID: 3240)
deploy@smoke-smoke-666 ~ $ sudo /etc/init.d/instrumentald start
"instrumentald" is already running (PID: 3240)
/opt/instrumentald/lib/app/bin/instrumentald:231:in `waitpid': No child processes (Errno::ECHILD)
	from /opt/instrumentald/lib/app/bin/instrumentald:231:in `block in <main>'
	from /opt/instrumentald/lib/ruby/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /opt/instrumentald/lib/ruby/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	from /opt/instrumentald/lib/ruby/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /opt/instrumentald/lib/ruby/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /opt/instrumentald/lib/ruby/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	from /opt/instrumentald/lib/app/bin/instrumentald:230:in `<main>'
```

**Comment by jqr** [comment]
It seems like it's been a best practice to avoid these for some time ([12factor](http://12factor.net/concurrency), [Sailings](http://dustin.sallings.org/2010/02/28/running-processes.html), [Perham](https://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/), [default for systemd](https://www.freedesktop.org/software/systemd/man/systemd.service.html), etc.).

How about abandoning the daemon mode altogether? It requires a good amount of code and dependencies, is no longer a recommended practice, and provides for lots of obscure bugs like this one.

**Comment by jason-o-matic** [comment]
I'm not opposed in general, though this is the first I've really read about this new crazy future in which shit isn't all jank. From the links you pasted it sounds like a better way of handling things.

I'm still trying to figure out how our packaging system works in general, and how it fits together with the variety of different init systems, so at the moment I lean towards a smaller fix. Maybe once I have a better idea of how things work I'll poke at switching strategies, or someone who's more familiar can jump in if they're excited.
