### ISSUE TITLE
`api_key` should be `project_token`

### ISSUE THREAD

**Issue by tonydewan** [Instrumental/instrumentald#25]
With the expansion of the API we did earlier this year, we consolidated our nomenclature on:

- tokens not keys
- API Token for user's tokens, used for API access
- Project Token for authentication of metric-sending agents

Given that, we should at least change the user-facing bits to be `project_token` instead of `api_key`. Ideally, we change all the internal stuff too.

**Comment by janxious** [comment]
started doing this a bit in #27 but there's more to do
