### ISSUE TITLE
Upstream telegraf PR to allow more metrics

### ISSUE THREAD

**Issue by janxious** [Instrumental/instrumentald#28]
@tonydewan and I ran into an issue whilst trying to get #27 working. We need to upstream https://github.com/Instrumental/telegraf/pull/2 so we can get blockio stats out of docker.

**Comment by jqr** [comment]
I thought we were using our own version of telegraf that already includes that change?

**Comment by janxious** [comment]
That was definitely my expectation. It's possible the telegraf generated after the changes in https://github.com/Instrumental/telegraf/pull/2 never got pulled into this repo. I think we should upstream it regardless. It's on the top of my todo list for next week to see if we can workaround it in the meantime.

**Comment by janxious** [comment]
The referenced URL is gone, but I'm pretty sure we did it!
