### ISSUE TITLE
Disk metrics should include device name instead of mountpoint

### ISSUE THREAD

**Issue by tonydewan** [Instrumental/instrumentald#45]
As it stands now, disk metrics collected by `instrumentald` will look like:

```
system.<hostname>.disk.<mount-point>.<metric>
```

Where mount-point will look like `-`, `-boot`, etc. It would be more useful and readable if it used the device name instead, or:

```
system.<hostname>.disk.<device-name>.<metric>
```

**Comment by tonydewan** [comment]
We have a [PR outstanding](https://github.com/influxdata/telegraf/pull/1807) on telegraf to enable this change.

**Comment by janxious** [comment]
This was updated upstream inm telegraf and in instrumentald
