### ISSUE TITLE
Multiple vhosts on nginx?

### ISSUE THREAD

**Issue by mfalkvidd** [Instrumental/instrumentald#83]
I am trying to monitor multiple vhosts on nginx.

My config (from instrumentald.toml):
```
nginx = ["https://a.example.com/status", "https://b.example.com/status"]
```

I get one set of nginx metrix on https://instrumentalapp.com, but I can't see for which vhost the data is. Is it the data from the first vhost, the second vhost or some merge of both? Should my configuration be different?

I would prefer to have one set of metrics for each vhost.

**Comment by mfalkvidd** [comment]
Sorry for the confusion. Both vhosts do become visible in metrics, just the way I wanted it.

**Comment by mediocretes** [comment]
Glad it worked out!  If you have other problems, feel free to make another issue, or hit the question mark button at the top right of the graph interface to talk to us directly.
